# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SelectDataWindowDesign.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(830, 420)
        self.horizontalLayout_2 = QtGui.QHBoxLayout(Dialog)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.buttonBox = QtGui.QDialogButtonBox(self.tab)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setGeometry(QtCore.QRect(580, 320, 181, 31))
        self.buttonBox.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.toolButton = QtGui.QToolButton(self.tab)
        self.toolButton.setGeometry(QtCore.QRect(740, 40, 31, 31))
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButton.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.chooseDataFolder = QtGui.QLineEdit(self.tab)
        self.chooseDataFolder.setGeometry(QtCore.QRect(220, 40, 501, 27))
        self.chooseDataFolder.setObjectName(_fromUtf8("chooseDataFolder"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(30, 40, 151, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(30, 180, 131, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(30, 220, 151, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.startTime = QtGui.QLineEdit(self.tab)
        self.startTime.setGeometry(QtCore.QRect(110, 280, 181, 27))
        self.startTime.setObjectName(_fromUtf8("startTime"))
        self.endTime = QtGui.QLineEdit(self.tab)
        self.endTime.setGeometry(QtCore.QRect(110, 320, 181, 27))
        self.endTime.setObjectName(_fromUtf8("endTime"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(30, 280, 91, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(30, 320, 91, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.chosseLidar = QtGui.QComboBox(self.tab)
        self.chosseLidar.setGeometry(QtCore.QRect(200, 180, 131, 27))
        self.chosseLidar.setObjectName(_fromUtf8("chosseLidar"))
        self.chosseLidar.addItem(_fromUtf8(""))
        self.chosseLidar.setItemText(0, _fromUtf8(""))
        self.chosseLidar.addItem(_fromUtf8(""))
        self.chosseLidar.addItem(_fromUtf8(""))
        self.chosseLidar.addItem(_fromUtf8(""))
        self.chooseCamera = QtGui.QComboBox(self.tab)
        self.chooseCamera.setGeometry(QtCore.QRect(200, 220, 131, 27))
        self.chooseCamera.setObjectName(_fromUtf8("chooseCamera"))
        self.chooseCamera.addItem(_fromUtf8(""))
        self.chooseCamera.setItemText(0, _fromUtf8(""))
        self.chooseCamera.addItem(_fromUtf8(""))
        self.chooseCamera.addItem(_fromUtf8(""))
        self.chooseCamera.addItem(_fromUtf8(""))
        self.chooseCamera.addItem(_fromUtf8(""))
        self.chooseCamera.addItem(_fromUtf8(""))
        self.chooseCamera.addItem(_fromUtf8(""))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(30, 80, 191, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(30, 120, 171, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.chooseExtrFolder = QtGui.QLineEdit(self.tab)
        self.chooseExtrFolder.setGeometry(QtCore.QRect(220, 80, 501, 27))
        self.chooseExtrFolder.setObjectName(_fromUtf8("chooseExtrFolder"))
        self.chooseModelsFolder = QtGui.QLineEdit(self.tab)
        self.chooseModelsFolder.setGeometry(QtCore.QRect(220, 120, 501, 27))
        self.chooseModelsFolder.setObjectName(_fromUtf8("chooseModelsFolder"))
        self.toolButton_2 = QtGui.QToolButton(self.tab)
        self.toolButton_2.setGeometry(QtCore.QRect(740, 80, 31, 31))
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButton_2.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.toolButton_3 = QtGui.QToolButton(self.tab)
        self.toolButton_3.setGeometry(QtCore.QRect(740, 120, 31, 31))
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButton_3.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton_3.setObjectName(_fromUtf8("toolButton_3"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.buttonBox_2 = QtGui.QDialogButtonBox(self.tab_2)
        self.buttonBox_2.setGeometry(QtCore.QRect(610, 440, 176, 27))
        self.buttonBox_2.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_2.setObjectName(_fromUtf8("buttonBox_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), self.chooseDataFolder.clear)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), self.chosseLidar.clear)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), self.chooseCamera.clear)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), self.startTime.clear)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), self.endTime.clear)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.tabWidget.setToolTip(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>", None))
        self.tabWidget.setWhatsThis(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>", None))
        self.toolButton.setText(_translate("Dialog", "...", None))
        self.label.setText(_translate("Dialog", "Choose Data Folder:", None))
        self.label_2.setText(_translate("Dialog", "Choose Lidar Data:", None))
        self.label_3.setText(_translate("Dialog", "Choose Camera Data:", None))
        self.label_4.setText(_translate("Dialog", "Start time:", None))
        self.label_5.setText(_translate("Dialog", "End time:", None))
        self.chosseLidar.setItemText(1, _translate("Dialog", "lms_front", None))
        self.chosseLidar.setItemText(2, _translate("Dialog", "ldmrs", None))
        self.chosseLidar.setItemText(3, _translate("Dialog", "lms_rear", None))
        self.chooseCamera.setItemText(1, _translate("Dialog", "mono_left", None))
        self.chooseCamera.setItemText(2, _translate("Dialog", "mono_rear", None))
        self.chooseCamera.setItemText(3, _translate("Dialog", "mono_right", None))
        self.chooseCamera.setItemText(4, _translate("Dialog", "stereo_left", None))
        self.chooseCamera.setItemText(5, _translate("Dialog", "stereo_center", None))
        self.chooseCamera.setItemText(6, _translate("Dialog", "stereo_right", None))
        self.label_6.setText(_translate("Dialog", "Choose Extrinsics Folder:", None))
        self.label_7.setText(_translate("Dialog", "Choose Models Folder:", None))
        self.toolButton_2.setText(_translate("Dialog", "...", None))
        self.toolButton_3.setText(_translate("Dialog", "...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "RobotCarDataSet data", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Custom data", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

