# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SelectDataWindowDesign.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(943, 766)
        self.horizontalLayout_2 = QtGui.QHBoxLayout(Dialog)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.buttonBoxDataSet = QtGui.QDialogButtonBox(self.tab)
        self.buttonBoxDataSet.setEnabled(True)
        self.buttonBoxDataSet.setGeometry(QtCore.QRect(680, 650, 181, 31))
        self.buttonBoxDataSet.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.buttonBoxDataSet.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBoxDataSet.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBoxDataSet.setCenterButtons(False)
        self.buttonBoxDataSet.setObjectName(_fromUtf8("buttonBoxDataSet"))
        self.browseButton1 = QtGui.QToolButton(self.tab)
        self.browseButton1.setGeometry(QtCore.QRect(760, 40, 31, 31))
        self.browseButton1.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.browseButton1.setArrowType(QtCore.Qt.NoArrow)
        self.browseButton1.setObjectName(_fromUtf8("browseButton1"))
        self.chooseDataFolder = QtGui.QLineEdit(self.tab)
        self.chooseDataFolder.setGeometry(QtCore.QRect(240, 40, 501, 27))
        self.chooseDataFolder.setObjectName(_fromUtf8("chooseDataFolder"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(50, 40, 151, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(50, 180, 131, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(50, 220, 151, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.startTimeF = QtGui.QLineEdit(self.tab)
        self.startTimeF.setGeometry(QtCore.QRect(240, 320, 181, 27))
        self.startTimeF.setWhatsThis(_fromUtf8(""))
        self.startTimeF.setObjectName(_fromUtf8("startTimeF"))
        self.endTimeF = QtGui.QLineEdit(self.tab)
        self.endTimeF.setGeometry(QtCore.QRect(240, 360, 181, 27))
        self.endTimeF.setObjectName(_fromUtf8("endTimeF"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(50, 320, 111, 17))
        self.label_4.setWhatsThis(_fromUtf8(""))
        self.label_4.setAccessibleDescription(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(50, 360, 111, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.chooseLidar = QtGui.QComboBox(self.tab)
        self.chooseLidar.setGeometry(QtCore.QRect(240, 180, 131, 27))
        self.chooseLidar.setObjectName(_fromUtf8("chooseLidar"))
        self.chooseLidar.addItem(_fromUtf8(""))
        self.chooseLidar.setItemText(0, _fromUtf8(""))
        self.chooseLidar.addItem(_fromUtf8(""))
        self.chooseLidar.addItem(_fromUtf8(""))
        self.chooseLidar.addItem(_fromUtf8(""))
        self.chooseCamera = QtGui.QComboBox(self.tab)
        self.chooseCamera.setGeometry(QtCore.QRect(240, 220, 131, 27))
        self.chooseCamera.setObjectName(_fromUtf8("chooseCamera"))
        self.chooseCamera.addItem(_fromUtf8(""))
        self.chooseCamera.setItemText(0, _fromUtf8(""))
        self.chooseCamera.addItem(_fromUtf8(""))
        self.chooseCamera.addItem(_fromUtf8(""))
        self.chooseCamera.addItem(_fromUtf8(""))
        self.chooseCamera.addItem(_fromUtf8(""))
        self.chooseCamera.addItem(_fromUtf8(""))
        self.chooseCamera.addItem(_fromUtf8(""))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(50, 80, 191, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(50, 120, 171, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.chooseExtrFolder = QtGui.QLineEdit(self.tab)
        self.chooseExtrFolder.setGeometry(QtCore.QRect(240, 80, 501, 27))
        self.chooseExtrFolder.setObjectName(_fromUtf8("chooseExtrFolder"))
        self.chooseModelsFolder = QtGui.QLineEdit(self.tab)
        self.chooseModelsFolder.setGeometry(QtCore.QRect(240, 120, 501, 27))
        self.chooseModelsFolder.setObjectName(_fromUtf8("chooseModelsFolder"))
        self.browseButton2 = QtGui.QToolButton(self.tab)
        self.browseButton2.setGeometry(QtCore.QRect(760, 80, 31, 31))
        self.browseButton2.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.browseButton2.setArrowType(QtCore.Qt.NoArrow)
        self.browseButton2.setObjectName(_fromUtf8("browseButton2"))
        self.browseButton3 = QtGui.QToolButton(self.tab)
        self.browseButton3.setGeometry(QtCore.QRect(760, 120, 31, 31))
        self.browseButton3.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.browseButton3.setArrowType(QtCore.Qt.NoArrow)
        self.browseButton3.setObjectName(_fromUtf8("browseButton3"))
        self.choosePoseF = QtGui.QComboBox(self.tab)
        self.choosePoseF.setGeometry(QtCore.QRect(240, 260, 131, 27))
        self.choosePoseF.setObjectName(_fromUtf8("choosePoseF"))
        self.choosePoseF.addItem(_fromUtf8(""))
        self.choosePoseF.setItemText(0, _fromUtf8(""))
        self.choosePoseF.addItem(_fromUtf8(""))
        self.choosePoseF.addItem(_fromUtf8(""))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(50, 260, 151, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.distortBox = QtGui.QCheckBox(self.tab)
        self.distortBox.setGeometry(QtCore.QRect(50, 470, 141, 22))
        self.distortBox.setObjectName(_fromUtf8("distortBox"))
        self.pointToImageBox = QtGui.QCheckBox(self.tab)
        self.pointToImageBox.setGeometry(QtCore.QRect(190, 470, 211, 22))
        self.pointToImageBox.setObjectName(_fromUtf8("pointToImageBox"))
        self.label_16 = QtGui.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(50, 440, 171, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.startTimeImg = QtGui.QLineEdit(self.tab)
        self.startTimeImg.setGeometry(QtCore.QRect(280, 510, 181, 27))
        self.startTimeImg.setWhatsThis(_fromUtf8(""))
        self.startTimeImg.setObjectName(_fromUtf8("startTimeImg"))
        self.label_17 = QtGui.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(50, 510, 201, 17))
        self.label_17.setWhatsThis(_fromUtf8(""))
        self.label_17.setAccessibleDescription(_fromUtf8(""))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(50, 550, 201, 17))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.endTimeImg = QtGui.QLineEdit(self.tab)
        self.endTimeImg.setGeometry(QtCore.QRect(280, 550, 181, 27))
        self.endTimeImg.setObjectName(_fromUtf8("endTimeImg"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(0, 10, 921, 20))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.chooseLidarData = QtGui.QLineEdit(self.tab_2)
        self.chooseLidarData.setGeometry(QtCore.QRect(240, 40, 501, 27))
        self.chooseLidarData.setObjectName(_fromUtf8("chooseLidarData"))
        self.choosePoseDataVo = QtGui.QLineEdit(self.tab_2)
        self.choosePoseDataVo.setGeometry(QtCore.QRect(240, 170, 501, 27))
        self.choosePoseDataVo.setObjectName(_fromUtf8("choosePoseDataVo"))
        self.browseButton6 = QtGui.QToolButton(self.tab_2)
        self.browseButton6.setGeometry(QtCore.QRect(750, 170, 31, 31))
        self.browseButton6.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.browseButton6.setArrowType(QtCore.Qt.NoArrow)
        self.browseButton6.setObjectName(_fromUtf8("browseButton6"))
        self.browseButton7 = QtGui.QToolButton(self.tab_2)
        self.browseButton7.setGeometry(QtCore.QRect(750, 200, 31, 31))
        self.browseButton7.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.browseButton7.setArrowType(QtCore.Qt.NoArrow)
        self.browseButton7.setObjectName(_fromUtf8("browseButton7"))
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(50, 170, 191, 20))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.browseButton4 = QtGui.QToolButton(self.tab_2)
        self.browseButton4.setGeometry(QtCore.QRect(750, 40, 31, 31))
        self.browseButton4.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.browseButton4.setArrowType(QtCore.Qt.NoArrow)
        self.browseButton4.setObjectName(_fromUtf8("browseButton4"))
        self.choosePoseExtrVo = QtGui.QLineEdit(self.tab_2)
        self.choosePoseExtrVo.setGeometry(QtCore.QRect(240, 200, 501, 27))
        self.choosePoseExtrVo.setObjectName(_fromUtf8("choosePoseExtrVo"))
        self.label_11 = QtGui.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(50, 200, 191, 20))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(50, 40, 151, 20))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(50, 70, 151, 20))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.browseButton5 = QtGui.QToolButton(self.tab_2)
        self.browseButton5.setGeometry(QtCore.QRect(750, 70, 31, 31))
        self.browseButton5.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.browseButton5.setArrowType(QtCore.Qt.NoArrow)
        self.browseButton5.setObjectName(_fromUtf8("browseButton5"))
        self.chooseLidarExtr = QtGui.QLineEdit(self.tab_2)
        self.chooseLidarExtr.setGeometry(QtCore.QRect(240, 70, 501, 27))
        self.chooseLidarExtr.setObjectName(_fromUtf8("chooseLidarExtr"))
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(0, 140, 921, 20))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.choosePoseKind = QtGui.QComboBox(self.tab_2)
        self.choosePoseKind.setGeometry(QtCore.QRect(240, 340, 131, 27))
        self.choosePoseKind.setObjectName(_fromUtf8("choosePoseKind"))
        self.choosePoseKind.addItem(_fromUtf8(""))
        self.choosePoseKind.setItemText(0, _fromUtf8(""))
        self.choosePoseKind.addItem(_fromUtf8(""))
        self.choosePoseKind.addItem(_fromUtf8(""))
        self.choosePoseKind.addItem(_fromUtf8(""))
        self.label_29 = QtGui.QLabel(self.tab_2)
        self.label_29.setGeometry(QtCore.QRect(50, 340, 151, 20))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.buttonBoxCustom = QtGui.QDialogButtonBox(self.tab_2)
        self.buttonBoxCustom.setEnabled(True)
        self.buttonBoxCustom.setGeometry(QtCore.QRect(680, 650, 181, 31))
        self.buttonBoxCustom.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.buttonBoxCustom.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBoxCustom.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBoxCustom.setCenterButtons(False)
        self.buttonBoxCustom.setObjectName(_fromUtf8("buttonBoxCustom"))
        self.label_30 = QtGui.QLabel(self.tab_2)
        self.label_30.setGeometry(QtCore.QRect(50, 380, 151, 20))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.clearHeight = QtGui.QCheckBox(self.tab_2)
        self.clearHeight.setGeometry(QtCore.QRect(240, 380, 101, 22))
        self.clearHeight.setObjectName(_fromUtf8("clearHeight"))
        self.label_31 = QtGui.QLabel(self.tab_2)
        self.label_31.setGeometry(QtCore.QRect(50, 100, 171, 17))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.synchLidarTime = QtGui.QLineEdit(self.tab_2)
        self.synchLidarTime.setGeometry(QtCore.QRect(240, 100, 181, 27))
        self.synchLidarTime.setText(_fromUtf8(""))
        self.synchLidarTime.setObjectName(_fromUtf8("synchLidarTime"))
        self.label_32 = QtGui.QLabel(self.tab_2)
        self.label_32.setGeometry(QtCore.QRect(50, 290, 161, 17))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.synchPoseTime = QtGui.QLineEdit(self.tab_2)
        self.synchPoseTime.setGeometry(QtCore.QRect(240, 290, 181, 27))
        self.synchPoseTime.setText(_fromUtf8(""))
        self.synchPoseTime.setObjectName(_fromUtf8("synchPoseTime"))
        self.label_33 = QtGui.QLabel(self.tab_2)
        self.label_33.setGeometry(QtCore.QRect(50, 430, 111, 17))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_34 = QtGui.QLabel(self.tab_2)
        self.label_34.setGeometry(QtCore.QRect(50, 460, 161, 17))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.endTimeCustom = QtGui.QLineEdit(self.tab_2)
        self.endTimeCustom.setGeometry(QtCore.QRect(240, 460, 181, 27))
        self.endTimeCustom.setObjectName(_fromUtf8("endTimeCustom"))
        self.startTimeCustom = QtGui.QLineEdit(self.tab_2)
        self.startTimeCustom.setGeometry(QtCore.QRect(240, 430, 181, 27))
        self.startTimeCustom.setObjectName(_fromUtf8("startTimeCustom"))
        self.clearRoll = QtGui.QCheckBox(self.tab_2)
        self.clearRoll.setGeometry(QtCore.QRect(390, 380, 81, 22))
        self.clearRoll.setObjectName(_fromUtf8("clearRoll"))
        self.clearPitch = QtGui.QCheckBox(self.tab_2)
        self.clearPitch.setGeometry(QtCore.QRect(520, 380, 101, 22))
        self.clearPitch.setObjectName(_fromUtf8("clearPitch"))
        self.skalaVO = QtGui.QLineEdit(self.tab_2)
        self.skalaVO.setGeometry(QtCore.QRect(490, 340, 111, 27))
        self.skalaVO.setText(_fromUtf8(""))
        self.skalaVO.setObjectName(_fromUtf8("skalaVO"))
        self.label_38 = QtGui.QLabel(self.tab_2)
        self.label_38.setGeometry(QtCore.QRect(420, 340, 91, 20))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_19 = QtGui.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(0, 510, 921, 20))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.browseButton8 = QtGui.QToolButton(self.tab_2)
        self.browseButton8.setGeometry(QtCore.QRect(790, 540, 31, 31))
        self.browseButton8.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.browseButton8.setArrowType(QtCore.Qt.NoArrow)
        self.browseButton8.setObjectName(_fromUtf8("browseButton8"))
        self.label_20 = QtGui.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(50, 540, 121, 20))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.chooseImgData = QtGui.QLineEdit(self.tab_2)
        self.chooseImgData.setGeometry(QtCore.QRect(280, 540, 501, 27))
        self.chooseImgData.setObjectName(_fromUtf8("chooseImgData"))
        self.label_61 = QtGui.QLabel(self.tab_2)
        self.label_61.setGeometry(QtCore.QRect(50, 570, 201, 17))
        self.label_61.setWhatsThis(_fromUtf8(""))
        self.label_61.setAccessibleDescription(_fromUtf8(""))
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.startTimeImgCustom = QtGui.QLineEdit(self.tab_2)
        self.startTimeImgCustom.setGeometry(QtCore.QRect(280, 570, 181, 27))
        self.startTimeImgCustom.setWhatsThis(_fromUtf8(""))
        self.startTimeImgCustom.setObjectName(_fromUtf8("startTimeImgCustom"))
        self.pointToImageBoxCustom = QtGui.QCheckBox(self.tab_2)
        self.pointToImageBoxCustom.setGeometry(QtCore.QRect(520, 590, 211, 22))
        self.pointToImageBoxCustom.setToolTip(_fromUtf8(""))
        self.pointToImageBoxCustom.setChecked(False)
        self.pointToImageBoxCustom.setObjectName(_fromUtf8("pointToImageBoxCustom"))
        self.endTimeImgCustom = QtGui.QLineEdit(self.tab_2)
        self.endTimeImgCustom.setGeometry(QtCore.QRect(280, 600, 181, 27))
        self.endTimeImgCustom.setObjectName(_fromUtf8("endTimeImgCustom"))
        self.label_62 = QtGui.QLabel(self.tab_2)
        self.label_62.setGeometry(QtCore.QRect(50, 600, 201, 17))
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.label_39 = QtGui.QLabel(self.tab_2)
        self.label_39.setGeometry(QtCore.QRect(650, 340, 91, 20))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.beta = QtGui.QLineEdit(self.tab_2)
        self.beta.setGeometry(QtCore.QRect(700, 340, 111, 27))
        self.beta.setText(_fromUtf8(""))
        self.beta.setObjectName(_fromUtf8("beta"))
        self.label_55 = QtGui.QLabel(self.tab_2)
        self.label_55.setGeometry(QtCore.QRect(50, 230, 191, 20))
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.browseButton9 = QtGui.QToolButton(self.tab_2)
        self.browseButton9.setGeometry(QtCore.QRect(750, 230, 31, 31))
        self.browseButton9.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.browseButton9.setArrowType(QtCore.Qt.NoArrow)
        self.browseButton9.setObjectName(_fromUtf8("browseButton9"))
        self.choosePoseDataImu = QtGui.QLineEdit(self.tab_2)
        self.choosePoseDataImu.setGeometry(QtCore.QRect(240, 230, 501, 27))
        self.choosePoseDataImu.setObjectName(_fromUtf8("choosePoseDataImu"))
        self.choosePoseExtrImu = QtGui.QLineEdit(self.tab_2)
        self.choosePoseExtrImu.setGeometry(QtCore.QRect(240, 260, 501, 27))
        self.choosePoseExtrImu.setObjectName(_fromUtf8("choosePoseExtrImu"))
        self.browseButton10 = QtGui.QToolButton(self.tab_2)
        self.browseButton10.setGeometry(QtCore.QRect(750, 260, 31, 31))
        self.browseButton10.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.browseButton10.setArrowType(QtCore.Qt.NoArrow)
        self.browseButton10.setObjectName(_fromUtf8("browseButton10"))
        self.label_56 = QtGui.QLabel(self.tab_2)
        self.label_56.setGeometry(QtCore.QRect(50, 260, 191, 20))
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBoxDataSet, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBoxDataSet, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QObject.connect(self.buttonBoxCustom, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBoxCustom, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QObject.connect(self.pointToImageBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.distortBox.setChecked)
        QtCore.QObject.connect(self.pointToImageBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.distortBox.setDisabled)
        QtCore.QObject.connect(self.pointToImageBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.startTimeImg.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Wybór danych", None))
        self.tabWidget.setToolTip(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>", None))
        self.tabWidget.setWhatsThis(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>", None))
        self.buttonBoxDataSet.setToolTip(_translate("Dialog", "<html><head/><body><p>\"OK\" - zapis zmian w obu zakładkach i wybór danych z projektu RobotCar DataSet do wyświetlenia.</p></body></html>", None))
        self.browseButton1.setToolTip(_translate("Dialog", "<html><head/><body><p>Przycisk \"Browse\".</p></body></html>", None))
        self.browseButton1.setText(_translate("Dialog", "...", None))
        self.chooseDataFolder.setToolTip(_translate("Dialog", "<html><head/><body><p>Ścieżka do folderu zawierajacego wszystkie dane z jednego przejazdu.</p></body></html>", None))
        self.label.setToolTip(_translate("Dialog", "Ścieżka do folderu zawierajacego wszystkie dane z jednego przejazdu.", None))
        self.label.setText(_translate("Dialog", "Folder danych:", None))
        self.label_2.setText(_translate("Dialog", "Wybierz lidar:", None))
        self.label_3.setText(_translate("Dialog", "Wybierz kamerę:", None))
        self.startTimeF.setToolTip(_translate("Dialog", "Czas pomiaru z lidaru od którego zaczyna się budowanie pointcloudu, relatywny do pierwszego pomiaru z lidaru", None))
        self.endTimeF.setToolTip(_translate("Dialog", "Czas pomiaru z lidaru na którym ma się zakończyć budowanie pointcloudu, relatywny do pierwszego pomiaru z lidaru.", None))
        self.label_4.setToolTip(_translate("Dialog", "Czas pomiaru z lidaru od którego zaczyna się budowanie pointcloudu, relatywny do pierwszego pomiaru z lidaru", None))
        self.label_4.setText(_translate("Dialog", "Czas startu [ms]:", None))
        self.label_5.setToolTip(_translate("Dialog", "<html><head/><body><p>Czas pomiaru z lidaru na którym ma się zakończyć budowanie pointcloudu, relatywny do pierwszego pomiaru z lidaru.</p></body></html>", None))
        self.label_5.setText(_translate("Dialog", "Czas końca [ms]:", None))
        self.chooseLidar.setItemText(1, _translate("Dialog", "lms_front", None))
        self.chooseLidar.setItemText(2, _translate("Dialog", "ldmrs", None))
        self.chooseLidar.setItemText(3, _translate("Dialog", "lms_rear", None))
        self.chooseCamera.setItemText(1, _translate("Dialog", "mono_left", None))
        self.chooseCamera.setItemText(2, _translate("Dialog", "mono_rear", None))
        self.chooseCamera.setItemText(3, _translate("Dialog", "mono_right", None))
        self.chooseCamera.setItemText(4, _translate("Dialog", "stereo/left", None))
        self.chooseCamera.setItemText(5, _translate("Dialog", "stereo/centre", None))
        self.chooseCamera.setItemText(6, _translate("Dialog", "stereo/right", None))
        self.label_6.setToolTip(_translate("Dialog", "Ścieżka do folderu extrinsic.", None))
        self.label_6.setText(_translate("Dialog", "Folder extrinsic:", None))
        self.label_7.setToolTip(_translate("Dialog", "Ścieżka do folderu models.", None))
        self.label_7.setText(_translate("Dialog", "Folder modeli kamer:", None))
        self.chooseExtrFolder.setToolTip(_translate("Dialog", "<html><head/><body><p>Ścieżka do folderu extrinsic.</p></body></html>", None))
        self.chooseModelsFolder.setToolTip(_translate("Dialog", "<html><head/><body><p>Ścieżka do folderu models.</p></body></html>", None))
        self.browseButton2.setToolTip(_translate("Dialog", "<html><head/><body><p>Przycisk \"Browse\".</p></body></html>", None))
        self.browseButton2.setText(_translate("Dialog", "...", None))
        self.browseButton3.setToolTip(_translate("Dialog", "<html><head/><body><p>Przycisk \"Browse\".</p></body></html>", None))
        self.browseButton3.setText(_translate("Dialog", "...", None))
        self.choosePoseF.setItemText(1, _translate("Dialog", "ins.csv", None))
        self.choosePoseF.setItemText(2, _translate("Dialog", "vo.csv", None))
        self.label_8.setText(_translate("Dialog", "Wybierz plik pozycji:", None))
        self.distortBox.setText(_translate("Dialog", "Usuń dystorsję", None))
        self.pointToImageBox.setText(_translate("Dialog", "Nałóż punkty 3D na obraz", None))
        self.label_16.setText(_translate("Dialog", "Opcje danych z kamery:", None))
        self.startTimeImg.setToolTip(_translate("Dialog", "<html><head/><body><p>Czas pierwszego zdjęcia do wyswietlenia, relatywny względem czasu startu. W przypadku nakładania punktów 3d na obraz jest on równy 0.</p></body></html>", None))
        self.label_17.setToolTip(_translate("Dialog", "<html><head/><body><p>Czas pierwszego zdjęcia do wyswietlenia, relatywny względem czasu startu. W przypadku nakładania punktów 3d na obraz jest on równy 0.</p></body></html>", None))
        self.label_17.setText(_translate("Dialog", "Czas pierwszego zdjęcia [ms]:", None))
        self.label_18.setToolTip(_translate("Dialog", "<html><head/><body><p>Czas ostatniego zdjęcia do wyswietlenia, relatywny względem czasu startu</p></body></html>", None))
        self.label_18.setText(_translate("Dialog", "Czas ostatniego zdjęcia [ms]:", None))
        self.endTimeImg.setToolTip(_translate("Dialog", "<html><head/><body><p>Czas ostatniego zdjęcia do wyswietlenia, relatywny względem czasu startu.</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Dane projektu RobotCar DataSet", None))
        self.label_9.setText(_translate("Dialog", "Lidar ", None))
        self.chooseLidarData.setToolTip(_translate("Dialog", "<html><head/><body><p>Ścieżka do pliku z danymi z lidaru (w formacie csv).</p></body></html>", None))
        self.choosePoseDataVo.setToolTip(_translate("Dialog", "<html><head/><body><p>Ścieżka do pliku pozycji (w formacie csv) wygenerowanym za pomocą odometrii wizyjnej.</p></body></html>", None))
        self.browseButton6.setToolTip(_translate("Dialog", "<html><head/><body><p>Przycisk \"Browse\".</p></body></html>", None))
        self.browseButton6.setText(_translate("Dialog", "...", None))
        self.browseButton7.setToolTip(_translate("Dialog", "<html><head/><body><p>Przycisk \"Browse\".</p></body></html>", None))
        self.browseButton7.setText(_translate("Dialog", "...", None))
        self.label_10.setToolTip(_translate("Dialog", "Ścieżka do pliku pozycji (w formacie csv) wygenerowanym za pomocą odometrii wizyjnej.", None))
        self.label_10.setText(_translate("Dialog", "Plik pozycji vo:", None))
        self.browseButton4.setToolTip(_translate("Dialog", "<html><head/><body><p>Przycisk \"Browse\".</p></body></html>", None))
        self.browseButton4.setText(_translate("Dialog", "...", None))
        self.choosePoseExtrVo.setToolTip(_translate("Dialog", "<html><head/><body><p>Ścieżka do pliku extrinsic (w formacie txt) określającego orientację układu współrzędnych vo względem układu bazowego.</p></body></html>", None))
        self.label_11.setToolTip(_translate("Dialog", "Ścieżka do pliku extrinsic (w formacie txt) określającego orientację układu współrzędnych vo względem układu bazowego.", None))
        self.label_11.setText(_translate("Dialog", "Plik extrinsic vo:", None))
        self.label_12.setToolTip(_translate("Dialog", "Ścieżka do pliku z danymi z lidaru (w formacie csv).", None))
        self.label_12.setText(_translate("Dialog", "Plik lidaru:", None))
        self.label_13.setToolTip(_translate("Dialog", "Ścieżka do pliku extrinsic (w formacie txt) określającego orientację układu lidaru względem układu bazowego.", None))
        self.label_13.setText(_translate("Dialog", "Plik extrinsic:", None))
        self.browseButton5.setToolTip(_translate("Dialog", "<html><head/><body><p>Przycisk \"Browse\".</p></body></html>", None))
        self.browseButton5.setText(_translate("Dialog", "...", None))
        self.chooseLidarExtr.setToolTip(_translate("Dialog", "<html><head/><body><p>Ścieżka do pliku extrinsic (w formacie txt) określającego orientację układu lidaru względem układu bazowego.</p></body></html>", None))
        self.label_14.setText(_translate("Dialog", "Pozycje", None))
        self.choosePoseKind.setToolTip(_translate("Dialog", "<html><head/><body><p>Wybór danych do wygenerowania pliku pozycji pointclouda.</p></body></html>", None))
        self.choosePoseKind.setItemText(1, _translate("Dialog", "vo", None))
        self.choosePoseKind.setItemText(2, _translate("Dialog", "vo + imu", None))
        self.choosePoseKind.setItemText(3, _translate("Dialog", "gps + imu", None))
        self.label_29.setText(_translate("Dialog", "Rodzaj pliku:", None))
        self.buttonBoxCustom.setToolTip(_translate("Dialog", "<html><head/><body><p>\"OK\" - zapis zmian w obu zakładkach i wybór własnych danych do wyświetlenia.</p></body></html>", None))
        self.label_30.setText(_translate("Dialog", "Zeruj:", None))
        self.clearHeight.setText(_translate("Dialog", "Wysokość", None))
        self.label_31.setToolTip(_translate("Dialog", "Czas służacy do synchronizacji danych z lidaru i pliku pozycji. Określa ile początkowych ms danych ma zostać pominiętych podczas wyświetlania danych z lidaru.", None))
        self.label_31.setText(_translate("Dialog", "Czas synchronizacji[ms]:", None))
        self.synchLidarTime.setToolTip(_translate("Dialog", "<html><head/><body><p>Czas służacy do synchronizacji danych z lidaru i pliku pozycji. Określa ile początkowych ms danych ma zostać pominiętych podczas wyświetlania danych z lidaru.</p></body></html>", None))
        self.label_32.setToolTip(_translate("Dialog", "Czas służacy do synchronizacji danych z lidaru i pliku pozycji. Określa ile początkowych ms danych ma zostać pominiętych podczas generowania pliku pozycji pointclouda.", None))
        self.label_32.setText(_translate("Dialog", "Czas synchronizacji[ms]:", None))
        self.synchPoseTime.setToolTip(_translate("Dialog", "<html><head/><body><p>Czas służacy do synchronizacji danych z lidaru i pliku pozycji. Określa ile początkowych ms danych ma zostać pominiętych podczas generowania pliku pozycji pointclouda.</p></body></html>", None))
        self.label_33.setToolTip(_translate("Dialog", "<html><head/><body><p>Czas pomiaru z lidaru od którego zaczyna się budowanie pointcloudu, relatywny do pierwszego pomiaru z lidaru</p></body></html>", None))
        self.label_33.setText(_translate("Dialog", "Czas startu [ms]:", None))
        self.label_34.setToolTip(_translate("Dialog", "<html><head/><body><p>Czas pomiaru z lidaru na którym ma się zakończyć budowanie pointcloudu, relatywny do pierwszego pomiaru z lidaru.</p></body></html>", None))
        self.label_34.setText(_translate("Dialog", "Czas zakończenia[ms]:", None))
        self.endTimeCustom.setToolTip(_translate("Dialog", "<html><head/><body><p>Czas pomiaru z lidaru na którym ma się zakończyć budowanie pointcloudu, relatywny do pierwszego pomiaru z lidaru.</p></body></html>", None))
        self.startTimeCustom.setToolTip(_translate("Dialog", "<html><head/><body><p>Czas pomiaru z lidaru od którego zaczyna się budowanie pointcloudu, relatywny do pierwszego pomiaru z lidaru.</p></body></html>", None))
        self.clearRoll.setText(_translate("Dialog", "Kąt roll", None))
        self.clearPitch.setText(_translate("Dialog", "Kąt pitch", None))
        self.skalaVO.setToolTip(_translate("Dialog", "<html><head/><body><p>Współczynnik służący do zmiany globalnej skali trajektorii otrzymanej z odometrii wizyjnej. Każda współrzędna x,y,z trajektorii jest mnożona przez ten współczynnik.</p></body></html>", None))
        self.label_38.setToolTip(_translate("Dialog", "Współczynnik służący do zmiany globalnej skali trajektorii otrzymanej z odometrii wizyjnej. Każda współrzędna x,y,z trajektorii jest mnożona przez ten współczynnik.", None))
        self.label_38.setText(_translate("Dialog", "Skala vo:", None))
        self.label_19.setText(_translate("Dialog", "Obrazy z kamery", None))
        self.browseButton8.setToolTip(_translate("Dialog", "<html><head/><body><p>Przycisk \"Browse\".</p></body></html>", None))
        self.browseButton8.setText(_translate("Dialog", "...", None))
        self.label_20.setToolTip(_translate("Dialog", "Ścieżka do folderu ze zdjęciami. Format nazwy zdjęć: \"out%03d.png\', czyli np. out001.png", None))
        self.label_20.setText(_translate("Dialog", "Ścieżka do zdjęć:", None))
        self.chooseImgData.setToolTip(_translate("Dialog", "<html><head/><body><p>Ścieżka do folderu ze zdjęciami. Format nazwy zdjęć: &quot;out%03d.png\', czyli np. out001.png</p></body></html>", None))
        self.label_61.setToolTip(_translate("Dialog", "<html><head/><body><p>Czas pierwszego zdjęcia do wyswietlenia, relatywny względem czasu startu. W przypadku nakładania punktów 3d na obraz powinien być dobrany tak aby pierwsza klatka obrazu była zrobiona w tym samym czasie co pierwszy pomiar z lidaru.</p></body></html>", None))
        self.label_61.setText(_translate("Dialog", "Czas pierwszego zdjęcia [ms]:", None))
        self.startTimeImgCustom.setToolTip(_translate("Dialog", "<html><head/><body><p>Czas pierwszego zdjęcia do wyswietlenia, relatywny względem czasu startu. W przypadku nakładania punktów 3d na obraz powinien być dobrany tak aby pierwsza klatka obrazu była zrobiona w tym samym czasie co pierwszy pomiar z lidaru.</p></body></html>", None))
        self.pointToImageBoxCustom.setText(_translate("Dialog", "Nałóż punkty 3D na obraz", None))
        self.endTimeImgCustom.setToolTip(_translate("Dialog", "<html><head/><body><p>Czas ostatniego zdjęcia do wyswietlenia, relatywny względem czasu startu</p></body></html>", None))
        self.label_62.setToolTip(_translate("Dialog", "<html><head/><body><p>Czas ostatniego zdjęcia do wyswietlenia, relatywny względem czasu startu</p></body></html>", None))
        self.label_62.setText(_translate("Dialog", "Czas ostatniego zdjęcia [ms]:", None))
        self.label_39.setText(_translate("Dialog", "Beta:", None))
        self.beta.setToolTip(_translate("Dialog", "<html><head/><body><p>Współczynnik wzmocnienia służący do strojenia filtru Madgwicka.</p></body></html>", None))
        self.label_55.setToolTip(_translate("Dialog", "Ścieżka do pliku pozycji (w formacie csv) wygenerowanym na podstawie danych z gps-a i jednostki imu ", None))
        self.label_55.setText(_translate("Dialog", "Plik pozycji imu:", None))
        self.browseButton9.setToolTip(_translate("Dialog", "<html><head/><body><p>Przycisk \"Browse\".</p></body></html>", None))
        self.browseButton9.setText(_translate("Dialog", "...", None))
        self.choosePoseDataImu.setToolTip(_translate("Dialog", "<html><head/><body><p>Ścieżka do pliku pozycji (w formacie csv) wygenerowanym na podstawie danych z gps-a i jednostki imu </p></body></html>", None))
        self.choosePoseExtrImu.setToolTip(_translate("Dialog", "<html><head/><body><p>Ścieżka do pliku extrinsic (w formacie txt) określającego orientację układu współrzędnych imu względem układu bazowego.</p></body></html>", None))
        self.browseButton10.setToolTip(_translate("Dialog", "<html><head/><body><p>Przycisk \"Browse\".</p></body></html>", None))
        self.browseButton10.setText(_translate("Dialog", "...", None))
        self.label_56.setToolTip(_translate("Dialog", "Ścieżka do pliku extrinsic (w formacie txt) określającego orientację układu współrzędnych imu względem układu bazowego.", None))
        self.label_56.setText(_translate("Dialog", "Plik extrinsic imu:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Dane własne", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

